// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxlB9vy3uPfHTMKpQZAasoMNqhYa3V-8',
    appId: '1:117708430102:web:df4154fc11a70bf1e18e37',
    messagingSenderId: '117708430102',
    projectId: 'pet-guardian-ffe0a',
    authDomain: 'pet-guardian-ffe0a.firebaseapp.com',
    storageBucket: 'pet-guardian-ffe0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwWK5cgXEKO2Pjkc3Q9ybvB6yqxhza53I',
    appId: '1:117708430102:android:a4ec2b654b875bb0e18e37',
    messagingSenderId: '117708430102',
    projectId: 'pet-guardian-ffe0a',
    storageBucket: 'pet-guardian-ffe0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlTwj11iMZ-yITihkL9xJ1m3kTlaJ9MZU',
    appId: '1:117708430102:ios:741d4f966569bd1de18e37',
    messagingSenderId: '117708430102',
    projectId: 'pet-guardian-ffe0a',
    storageBucket: 'pet-guardian-ffe0a.appspot.com',
    iosClientId: '117708430102-shl7bnggo4jh1b3sigv517l3krijf804.apps.googleusercontent.com',
    iosBundleId: 'com.brunott98.petGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlTwj11iMZ-yITihkL9xJ1m3kTlaJ9MZU',
    appId: '1:117708430102:ios:a0d459cbda2180d1e18e37',
    messagingSenderId: '117708430102',
    projectId: 'pet-guardian-ffe0a',
    storageBucket: 'pet-guardian-ffe0a.appspot.com',
    iosClientId: '117708430102-cjhlaehim39r8im8ui02jg2qs3270rh3.apps.googleusercontent.com',
    iosBundleId: 'com.brunott98.petGuardian.RunnerTests',
  );
}
